-- Events Module
-- Username
-- October 25, 2022




local EventsModule = {}

EventsModule.DISPLAY_BLUR_EVENT = "DISPLAY_BLUR"
EventsModule.DISPLAY_INTERMISSION = "DISPLAY_INTERMISSION"
EventsModule.DISPLAY_SCORE = "DISPLAY_SCORE"
EventsModule.DISPLAY_TIMER_INFO = "DISPLAY_TIMER_INFO"
EventsModule.DISPLAY_VICTORY = "DISPLAY_VICTORY"
EventsModule.DISPLAY_WAITING_FOR_OTHER_PLAYERS = "DISPLAY_WAITING_FOR_OTHER_PLAYERS"
EventsModule.FETCH_CONFIG = "FETCH_CONFIG"
EventsModule.RESET_MOUSE_ICON = "RESET_MOUSE_ICON"
EventsModule.SET_BLUR_BLOCK = "SET_BLUR_BLOCK"


return EventsModule